---
# Desktop environment installation - XFCE (optimized for RDP performance)

- name: Install XFCE desktop environment
  apt:
    name:
      - xfce4
      - xfce4-goodies
      - lightdm
      - lightdm-gtk-greeter
    state: present
  register: desktop_install

- name: Configure LightDM as default display manager
  debconf:
    name: lightdm
    question: shared/default-x-display-manager
    value: lightdm
    vtype: select

- name: Ensure LightDM is enabled and will start on boot
  systemd:
    name: lightdm
    enabled: yes
    state: started
  ignore_errors: yes

- name: Set graphical target as default
  systemd:
    name: graphical.target
    enabled: yes
  ignore_errors: yes

- name: Create .xsessionrc for XFCE
  copy:
    content: |
      #!/bin/bash
      export DESKTOP_SESSION=xfce
      export XDG_CURRENT_DESKTOP=XFCE
    dest: /etc/skel/.xsessionrc
    mode: '0755'

- name: Display desktop installation status
  debug:
    msg: "XFCE desktop environment has been installed successfully"
